# Creating DataFrames

In [15]:
# Deprecated name - numpy.str
# NumPy scalar type names - numpy.str_
# https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [16]:
import pandas as pd
import numpy as np

In [17]:
data = np.random.random(size=(5, 3))
print(data)

# Common 2D array and columns method
df = pd.DataFrame(data=data, columns=["A", "B", "C"])
df

[[0.90480104 0.2835278  0.53772935]
 [0.6755413  0.86529656 0.16101478]
 [0.29725997 0.8411927  0.40410185]
 [0.13430827 0.88506201 0.32945264]
 [0.28808978 0.72374221 0.35910111]]


A         B         C
0  0.904801  0.283528  0.537729
1  0.675541  0.865297  0.161015
2  0.297260  0.841193  0.404102
3  0.134308  0.885062  0.329453
4  0.288090  0.723742  0.359101

In [18]:
# A dictionary of columns
df = pd.DataFrame(data={"A": [1, 2, 3], "B": ["Dillon", "Johan", "Nellie"]})
df

A       B
0  1  Dillon
1  2   Johan
2  3  Nellie

In [19]:
# Or a list of rows (ie tuples) with a dtype
dtype = [("A", np.int), ("B", (np.str, 20))]
data = np.array([(1, "Dillon"), (2, "Johan"), (3, "Nellie")], dtype=dtype)
df = pd.DataFrame(data)
df

C:\Users\dillon\AppData\Local\Temp\ipykernel_30992\3341161810.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = [("A", np.int), ("B", (np.str, 20))]
C:\Users\dillon\AppData\Local\Temp\ipykernel_30992\3341161810.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs

A       B
0  1  Dillon
1  2   Johan
2  3  Nellie

In [20]:
# Or a list of rows (ie tuples) with a dtype
dtype = [("A", np.str_), ("B", (np.str_, 20))]
data = np.array([(1, "Dillon"), (2, "Johan"), (3, "Nellie")], dtype=dtype)
df = pd.DataFrame(data)
df

A       B
0    Dillon
1     Johan
2    Nellie

In [22]:
# Or the dictionary based version of list of rows
data = [{"A": 1, "B": "Dillon"}, {"A": 2, "B": "Johan"}, {"A": 3, "B": "Nellie"}]
df = pd.DataFrame(data)
df

A       B
0  1  Dillon
1  2   Johan
2  3  Nellie