# NumPy Arrays

In [1]:
my_list = [1,2,3]
import numpy as np

In [2]:
arr = np.array(my_list)

arr

array([1, 2, 3])

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [4]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(9,5,5)

array([9., 8., 7., 6., 5.])

In [17]:
np.linspace(9,5,10)

array([9.        , 8.55555556, 8.11111111, 7.66666667, 7.22222222,
       6.77777778, 6.33333333, 5.88888889, 5.44444444, 5.        ])

In [18]:
np.linspace(9,5,100)

array([9.        , 8.95959596, 8.91919192, 8.87878788, 8.83838384,
       8.7979798 , 8.75757576, 8.71717172, 8.67676768, 8.63636364,
       8.5959596 , 8.55555556, 8.51515152, 8.47474747, 8.43434343,
       8.39393939, 8.35353535, 8.31313131, 8.27272727, 8.23232323,
       8.19191919, 8.15151515, 8.11111111, 8.07070707, 8.03030303,
       7.98989899, 7.94949495, 7.90909091, 7.86868687, 7.82828283,
       7.78787879, 7.74747475, 7.70707071, 7.66666667, 7.62626263,
       7.58585859, 7.54545455, 7.50505051, 7.46464646, 7.42424242,
       7.38383838, 7.34343434, 7.3030303 , 7.26262626, 7.22222222,
       7.18181818, 7.14141414, 7.1010101 , 7.06060606, 7.02020202,
       6.97979798, 6.93939394, 6.8989899 , 6.85858586, 6.81818182,
       6.77777778, 6.73737374, 6.6969697 , 6.65656566, 6.61616162,
       6.57575758, 6.53535354, 6.49494949, 6.45454545, 6.41414141,
       6.37373737, 6.33333333, 6.29292929, 6.25252525, 6.21212121,
       6.17171717, 6.13131313, 6.09090909, 6.05050505, 6.01010

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(4)

array([0.32839579, 0.54361516, 0.80300021, 0.47088993])

In [23]:
np.random.rand(5,5)

array([[0.00280828, 0.23208445, 0.11135339, 0.5575742 , 0.04011238],
       [0.71069444, 0.85454067, 0.9417612 , 0.16444049, 0.89296352],
       [0.37261748, 0.37124514, 0.75837205, 0.39827384, 0.56022446],
       [0.96412466, 0.93376092, 0.85395575, 0.93882507, 0.74299919],
       [0.20541055, 0.21324225, 0.83440192, 0.47483043, 0.01106674]])

In [25]:
np.random.rand(4,4)

array([[0.32219128, 0.01709206, 0.20851286, 0.77852095],
       [0.49377889, 0.7978375 , 0.15175148, 0.86334442],
       [0.32291358, 0.70296612, 0.34520847, 0.23183958],
       [0.06479032, 0.48162848, 0.55607406, 0.67504993]])

In [26]:
np.random.randint(1,100)

69

In [27]:
np.random.randint(1,100)

26

In [28]:
np.random.randint(1,100,10)

array([26, 15, 17,  2, 67, 71, 82, 13, 27, 20])

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr = np.random.randint(0,50,10)

ranarr

array([ 5, 26, 43, 20, 37,  4, 17, 19, 47, 14])

In [37]:
ranarr.max()

47

In [38]:
ranarr.min()

4

In [41]:
ranarr

array([ 5, 26, 43, 20, 37,  4, 17, 19, 47, 14])

In [42]:
ranarr.argmax()

8

In [43]:
ranarr.argmin()

5

In [44]:
arr.shape

(25,)

In [46]:
arr = np.arange(25)

In [48]:
arr = arr.reshape(5,5)

In [49]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
arr.shape

(5, 5)

In [51]:
arr.dtype

dtype('int32')

In [52]:
from numpy.random import randint

In [53]:
randint(2,10)

8