# NumPy Indexing and Selection

In [3]:
import numpy as np

In [7]:
arr = np.arange(0,11)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[8]

8

In [10]:
arr[1:5]

array([1, 2, 3, 4])

In [11]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [12]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [13]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [14]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [15]:
arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6]

In [19]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:] = 99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [23]:
arr_copy = arr.copy()

arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy[:] = 100


In [26]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d[0][0]

5

In [30]:
arr_2d[0]

array([ 5, 10, 15])

In [31]:
arr_2d[1][1]

25

In [32]:
arr_2d[2][1]

40

In [34]:
arr_2d[2][2]

45

In [35]:
arr_2d[2,2]

45

In [36]:
arr_2d[1,2]

30

In [37]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr_2d[:3,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [41]:
arr_2d[:3]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
arr = np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
bool_arr = arr > 5

In [45]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [47]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [48]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [49]:
arr[arr < 3]

array([1, 2])

In [50]:
arr_2d = np.arange(50)

In [51]:
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
arr_2d = np.arange(50).reshape(5,10)

In [53]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
arr_2d[1:3,]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [57]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])